import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form action="/api/contact" method="post">
          <label htmlFor="first">First name:</label>
          <input type="text" id="first" name="first" />
          <br />
          <label htmlFor="last">Last name:</label>
          <input type="text" id="last" name="last" />
          <br />
          <hr />
          <button type="submit">Contact</button>
        </form>
      </main>
    </div>
  );
}
